# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 498fbca45f8e1ee3f728ebc7934ca941a2ebab631d865f83463c26a10d31f968d40160362978cabc309fa6c58f2fa9ca22460976fb567798e9f8670154cc6f94

test:
  secret_key_base: 542e67ca4a06d14add179c38f02f3e6fd5695bc6d245d415f15a5688737c417db7a13057707ed1656dd2528664e41d186db730bf90faaea674f33df3015f76c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
